//SYNCRO
export const LOAD_CHATS_DATA = 'MESSANGER/LOAD_USER_DATA';
export const SET_CHATS_DATA = 'MESSANGER/SET_CHATS_DATA';
export const OPEN_CHAT_WITH_USER = 'USER/OPEN_CHAT_WITH_USER';
//SYNCRO

//ASYNCRO
export const REQUEST_CHATS_DATA = 'MESSANGER/REQUEST_CHATS_DATA'
//ASYNCRO
