export const SIGNIN_COMPLETE = 'APP/SIGNIN_COMPLETE';
export const SIGNOUT_COMPLETE = 'APP/SIGNOUT_COMPLETE';
export const SEARCH_USER = 'APP/SEARCH_USER'
export const LOAD_LIST = 'APP/LOAD_LIST'
export const CHANGE_USER = 'APP/CHANGE_USER'
