export const SHOW_ALERT_SUCCESS = 'AUTH/SHOW_ALERT_SUCCESS';
export const HIDE_ALERT__SUCCESS = 'AUTH/HIDE_ALERT__SUCCESS';
export const SHOW_ALERT_ERROR = 'AUTH/SHOW_ALERT_ERROR';
export const HIDE_ALERT_ERROR = 'AUTH/HIDE_ALERT_ERROR';
export const SIGNOUT_USER = 'AUTH/SIGNOUT';
export const SIGNIN_USER = 'AUTH/SIGNIN';
export const SIGNUP_USER = 'AUTH/SIGNUP';
export const FORGOT_USER = 'AUTH/FORGOT';

