//SYNCRO
export const SET_USER_DATA = 'USER/SET_USER_DATA';
export const SET_IMAGE_DATA = 'USER/SET_IMAGE_DATA';
export const SET_POST_DATA = 'USER/SET_POST_DATA';
export const SET_FRIENDS_DATA = 'USER/SET_FRIENDS_DATA'
export const SET_INFO_DATA = 'USER/SET_INFO_DATA'
export const LOAD_USER_DATA = 'USER/LOAD_USER_DATA';
export const EDITABLE_USER_DATA = 'USER/EDITABLE_USER_DATA';
//SYNCRO

//ASYNCRO
export const REQUEST_USER_DATA = 'USER/REQUEST_USER_DATA';
export const UPLOAD_USER_DATA = 'USER/UPLOAD_USER_DATA';
export const DELETE_USER_DATA = 'USER/DELETE_USER_DATA';
export const CHOISE_USER_AVATAR = 'USER/CHOISE_USER_AVATAR';
export const CHANGE_USER_PROFILE_INFO = 'USER/CHANGE_USER_PROFILE_INFO';
export const LOAD_FRIENDS = 'USER/LOAD_FRIEND';
export const ADD_TO_FRIENDS = 'USER/ADD_TO_FRIENDS';
export const OPEN_CHAT_WITH_USER = 'USER/OPEN_CHAT_WITH_USER';
export const REQUEST_CHATS_DATA = 'USER/REQUEST_CHATS_DATA'
export const ADD_POST = 'USER/ADD_POST';
export const GET_SEARCH_DATA = 'USER/SEARCH_USER_DATA';
//ASYNCRO
