export const GET_PROFILE_DATA = 'USER/GET_DATA';
export const GET_CLOSE_CHATS_DATA = 'USER/CLOSE_CHATS_DATA';
export const GET_OPEN_CHATS_DATA = 'USER/CLOSE_CHATS_DATA';
export const GET_IMAGE_DATA = 'USER/GET_IMAGE_DATA';
export const GET_AUDIO_DATA = 'USER/GET_AUDIO_DATA';
export const GET_SEARCH_DATA = 'USER/SEARCH_USER_DATA';

export const REQUEST_USER_DATA = 'USER/REQUEST_USER_DATA';

export const LOAD_USER_DATA = 'USER/LOAD_USER_DATA';

export const UPLOAD_USER_DATA = 'USER/UPLOAD_USER_DATA';
export const DELETE_USER_DATA = 'USER/DELETE_USER_DATA';

export const CHOISE_USER_AVATAR = 'USER/CHOISE_USER_AVATAR';

export const CHANGE_USER_PROFILE = 'USER/CHANGE_USER_PROFILE';

export const EDITABLE_USER_DATA = 'USER/EDITABLE_USER_DATA';
export const LOAD_FRIENDS = 'USER/LOAD_FRIEND'



export const ADD_TO_FRIENDS = 'USER/ADD_TO_FRIENDS';
export const OPEN_CHAT_WITH_USER = 'USER/OPEN_CHAT_WITH_USER';

export const UPDATE_FRIENDS = 'USER/UPDATE_FRIENDS';
